config/routes.rb
Rails.application.routes.draw do
  get "productbrand/show/gear_brand_id=:id" => "productbrand#show", :as => :productbrand
  get "producttype/show/gear_type_id=:id" => "producttype#show", :as => :producttype
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :chipus
  get "charts/index"
  get "charts/show"
  resources :orders
  # get "store/index"
  resources :line_items
  resources :carts
  resources :brands
  resources :types
  resources :gears
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "phanloai/mouse"
  get "phanloai/keyboard"
  get "phannsx/razer"
  get "phannsx/logitech"
  get "phannsx/corsair"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "store#index", as: "store_index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :gears
  validates :brandname, presence: true, length: {minimum: 5, maximum: 30}
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  $total

  def add_gear(gear)
    current_item = line_items.find_by(gear_id: gear.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(gear_id: gear.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
    $total = line_items.to_a.sum { |item| item.total_price }
  end

  def self.total
    return $total
  end
end

app/models/chipu.rb
class Chipu < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/gear.rb
class Gear < ApplicationRecord
  has_attached_file :image, styles: {medium: "10000x10000>", thumb: "10000x10000>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :brand
  belongs_to :type
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :name, presence: true, length: {minimum: 5, maximum: 20}
  validates :description, presence: true, length: {minimum: 10}
  validates :image, presence: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 1}
  validates :inventory, presence: true, numericality: {greater_than_or_equal_to: 1}
  include PgSearch
  pg_search_scope :search_name, against: [:name], using: {
                                  tsearch: {
                                    prefix: true,
                                  },
                                }

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Items present")
      throw :abort
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :gear, optional: true
  belongs_to :order, optional: true
  belongs_to :cart
  $total

  def total_price
    gear.price * quantity
    $total = gear.price * quantity
  end

  def self.total
    return $total
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  enum pay_type: {
         "Check" => "Check",
         "Credit card" => "Credit card",
         "Purchase order" => "Purchase order",
       }
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :gears
  validates :typename, presence: true, length: {minimum: 5, maximum: 30}
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Giỏ hàng hiện tại đang trống" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_index_url, notice: "Invalid cart"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/phanloai_helper.rb
module PhanloaiHelper
end

app/helpers/phannsx_helper.rb
module PhannsxHelper
end

app/helpers/productbrand_helper.rb
module ProductbrandHelper
end

app/helpers/producttype_helper.rb
module ProducttypeHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/template_helper.rb
module TemplateHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/carts/_cart.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <% unless cart.line_items.empty? %>
    <h2 style="color:#ffffff;padding-left:25%;">Your Cart</h2>
    
        <table class="w3-table-all w3-hoverable">
        <thead class="thead-dark">
            <tr>
                <th>Quanlity</th>
                <th>Name</th>
                <th>Price</th>
                
            </tr>
        </thead>
        <%= render(cart.line_items) %>
        
            
            
            <tr class="total_line">
                    <td colspan="2">Total</td>
                    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
            </tr>
                
            
            
            <% end %>
</table> 
<table class="with_2">
<tr>
            <th><%= button_to "Checkout", new_order_path, method: :get,:class=>"btn btn-success" %></th>
            <th><%= button_to 'Empty cart', cart, method: :delete,data: { confirm: 'Are you sure?' },:class=>"btn btn-default" %></th>
</tr>
</table>

<!--css for 2 button behind-->
<style>
table.with_2 {
    margin-left: 20%;
}
</style>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%=render @cart%>