config/routes.rb
Rails.application.routes.draw do
  get "productbrand/show/gear_brand_id=:id" => "productbrand#show", :as => :productbrand
  get "producttype/show/gear_type_id=:id" => "producttype#show", :as => :producttype
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :chipus
  get "charts/index"
  get "charts/show"
  resources :orders
  # get "store/index"
  resources :line_items
  resources :carts
  resources :brands
  resources :types
  resources :gears
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "phanloai/mouse"
  get "phanloai/keyboard"
  get "phannsx/razer"
  get "phannsx/logitech"
  get "phannsx/corsair"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "store#index", as: "store_index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :gears
  validates :brandname, presence: true, length: {minimum: 5, maximum: 30}
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  $total

  def add_gear(gear)
    current_item = line_items.find_by(gear_id: gear.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(gear_id: gear.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
    $total = line_items.to_a.sum { |item| item.total_price }
  end

  def self.total
    return $total
  end
end

app/models/chipu.rb
class Chipu < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/gear.rb
class Gear < ApplicationRecord
  has_attached_file :image, styles: {medium: "10000x10000>", thumb: "10000x10000>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :brand
  belongs_to :type
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :name, presence: true, length: {minimum: 5, maximum: 20}
  validates :description, presence: true, length: {minimum: 10}
  validates :image, presence: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 1}
  validates :inventory, presence: true, numericality: {greater_than_or_equal_to: 1}
  include PgSearch
  pg_search_scope :search_name, against: [:name], using: {
                                  tsearch: {
                                    prefix: true,
                                  },
                                }

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Items present")
      throw :abort
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :gear, optional: true
  belongs_to :order, optional: true
  belongs_to :cart
  $total

  def total_price
    gear.price * quantity
    $total = gear.price * quantity
  end

  def self.total
    return $total
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  enum pay_type: {
         "Check" => "Check",
         "Credit card" => "Credit card",
         "Purchase order" => "Purchase order",
       }
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :gears
  validates :typename, presence: true, length: {minimum: 5, maximum: 30}
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :authenticate_chipu!, except: [:show]
  before_action :set_gear, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart

  # GET /gears
  # GET /gears.json
  def index
    if params[:query].present?
      @gears = Gear.search_name(params[:query]).paginate(page: params[:page], per_page: 2)
    else
      @gears = Gear.all.paginate(page: params[:page], per_page: 2)
    end
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
  end

  # GET /gears/new
  def new
    @gear = Gear.new
    @brand = Brand.all
    @type = Type.all
  end

  # GET /gears/1/edit
  def edit
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(gear_params)
    @brand = Brand.all
    @type = Type.all
    respond_to do |format|
      if @gear.save
        format.html { redirect_to request.referrer }
        format.json
        format.html { redirect_to @gear, notice: "Gear was successfully created." }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gears/1
  # PATCH/PUT /gears/1.json
  def update
    respond_to do |format|
      if @gear.update(gear_params)
        format.html { redirect_to @gear, notice: "Gear was successfully updated." }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: "Gear was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gear
    @gear = Gear.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gear_params
    params.require(:gear).permit(:name, :description, :image_url, :price, :inventory, :image, :brand_id, :type_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/phanloai_helper.rb
module PhanloaiHelper
end

app/helpers/phannsx_helper.rb
module PhannsxHelper
end

app/helpers/productbrand_helper.rb
module ProductbrandHelper
end

app/helpers/producttype_helper.rb
module ProducttypeHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/template_helper.rb
module TemplateHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/gears/_form.html.erb
<%= form_for @gear, html: { multipart: true } do |form| %>

  <% if gear.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(gear.errors.count, "error") %> prohibited this gear from being saved:</h2>

      <ul>
        <% gear.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :name %>
          <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :description%>
          <%= form.text_area :description ,:size=>"40x10" %>
      </div>

      <div class="field">
        <%= form.label :image%>

          <%= form.file_field :image %>

      </div>

      <div class="field">
        <%= form.label :price %>
          <%= form.text_field :price %>
      </div>

      <div class="field">
        <%= form.label :inventory %>
          <%= form.text_field :inventory %>
      </div>
      
      <div class="field">
          <%= form.label :brand %>
          <!-- <%= form.collection_select :brand, Brand.order(:brandname),:id,:brandname, include_blank: true %> -->
          <%= form.select :brand_id, options_from_collection_for_select(Brand.all, :id, :brandname), {:include_blank => 'Please choose brand for gear'} %>
      </div>
      <div class="field">
          <%= form.label :type %>
          <!-- <%= form.collection_select(:type, Type.all, :id, :typename ) %> -->
          <%= form.select :type_id, options_from_collection_for_select(Type.all, :id, :typename), {:include_blank => 'Please choose type for gear'} %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>

app/views/gears/edit.html.erb
<h1>Editing Gear</h1>

<%= render 'form', gear: @gear %>

    <%= link_to 'Show', @gear %> |
        <%= link_to 'Back', gears_path %>

app/views/gears/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gears</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Inventory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gears.each do |gear| %>
      <tr>
        <td><%= gear.name %></td>
        <td><%= gear.description %></td>
        <td><%= gear.image_url %></td>
        <td><%= gear.price %></td>
        <td><%= gear.inventory %></td>
        <td><%= link_to 'Show', gear %></td>
        <td><%= link_to 'Edit', edit_gear_path(gear) %></td>
        <td><%= link_to 'Destroy', gear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gear', new_gear_path %>

app/views/gears/new.html.erb
<h1>New Gear</h1>

<%= render 'form', gear: @gear %>

<%= link_to 'Back', gears_path %>

app/views/gears/show.html.erb
<p id="notice"><%= notice %></p>


<!--
<%= link_to 'Edit', edit_gear_path(@gear) %> |
<%= link_to 'Back', gears_path %>
-->
<!--new -->
<div class="alert alert-danger alert-dismissable">
				<button aria-hidden="true" data-dismiss="alert" class="close" type="button"> Đóng </button>
				<h2 class="t-button"><span class="label label-danger">Chính sách ưu đãi khi mua hàng</span></h2>
        <br>
				<p>  Miễn phí giao hàng </p>
				<p>  Mua hàng  </p>
			
			</div>
<div id="ctl00_divCenter" class="col-main col-lg-9 col-xl-9 partner-main">
	
					        
					        
    
<div class="Module Module-127"><div class="ModuleContent">
<div id="ctl00_mainContent_ctl00_ctl00_pnlInnerWrap">
		
    
    <div itemscope="itemscope" itemtype="http://schema.org/Product">
  <div itemtype="http://schema.org/Organization" itemprop="brand" itemscope="itemscope">
    <meta itemprop="name" content="Vortex">
  </div>
  <div class="block-productsDetail">
    <div class="row">
      <div class="col-xs-12 col-md-7 col-lg-7">
        <a class="MagicZoom" id="imgProduct" data-options="zoomMode: off; cssClass: white-bg; hint: always; transitionEffect: false; lazyZoom: true; textExpandHint: Click phóng to" >
          <figure class="mz-figure white-bg mz-hover-zoom mz-no-zoom"><%= image_tag @gear.image.url(:medium),:class=>"hover-img"%><div class="mz-lens" style="top: 0px; transform: translate(-10000px, -10000px);"><img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" style="position: absolute; top: 0px; left: 0px; width: 599.984px; height: 599.984px;"></div><div class="mz-hint"></div></figure>
        <style>
        .hover-img:hover {
          -ms-transform: scale(1.5); /* IE 9 */
          -webkit-transform: scale(1.5); /* Safari 3-8 */
          transform: scale(1.5); 
        }
        </style>
        </a>
        
         <a class="order-prd" onclick="AjaxCheckout.prepareorder(this);return false;" data-productid="2301">  <%= button_to 'Add to Cart', line_items_path(gear_id: @gear),remote: true,:class=>"btn btn-warning" %></a>
 
      </div>   
      <h2><%= @gear.name.upcase %></h2>
      <br>
      <br>

      <div class="col-xs-12 col-md-5 col-lg-5">
        <div class="prd-content">
            <h5 class="title">-Type: <%=link_to  @gear.type.typename.upcase, producttype_path(@gear.type.typename)%>		</h5>
          
          <div class="briefContent"></div>
          <div class="brands prd-opt">
          </div> <div class="brands prd-opt">
            <h5 class="title">-Brand: <%=link_to @gear.brand.brandname.upcase, productbrand_path(@gear.brand.brandname)%></h5>
           
          </div></div> <div class="brands prd-opt">
            <h5 class="title">-Inventory: <%= @gear.inventory %></h5>
          </div>
          <div class="prd-price prd-opt">
            <div class="row">
              <div class="col-xs-12" itemscope="itemscope" itemprop="offers" itemtype="http://schema.org/Offer">
                <meta itemprop="priceCurrency" content="VND">
                <div class="price-new">
                  <h5 class="title">-Prise:  <span class="new-price" itemprop="price"> <%= number_to_currency(@gear.price, precision: 0, unit: "$", separator: ",") %>				</span></h5>
                 
                </div>
              </div>
            </div>
          </div>
          <div class="row order-support">
            <div class="col-xs-6">
              <div class="order-submit">
               
              </div>
               
            
            </div>
           
          </div>
             <div>
   <h5>Other type of gear same: </h5>
             <%@types.each do |type|%>
            <div class="button-square">
               <div class="gradient"></div>
            <%=link_to  type.typename.upcase, producttype_path(type.typename),:class=>"button-type"%>		     
            </div>
            <%end%>
            <br>
            <br>
            <br>
             <br>
           
             <h5>Other brand of gear same: </h5>
             <%@brands.each do |brand|%>
            <div class="button-square">
               <div class="gradient"></div>
            <%=link_to brand.brandname.upcase, productbrand_path(brand.brandname),:class=>"button-type"%>	     
            </div>
            <%end%>
            <div>
            
          
        
      </div>
    </div>
  </div>

  <div class="prd-desc">
    <div class="row">
      <div class="col-xs-12">
        <ul class="nav nav-tabs responsive" role="tablist">
          <li class="nav-item">
           <a class="nav-link active" role="tab" data-toggle="tab" href="#tab-1" aria-controls="tab-1" aria-expanded="true">Digital information</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" role="tab" data-toggle="tab" href="#tab-0" aria-controls="tab-0">Comment</a>
          </li>
        </ul>
        <div class="tab-content responsive">
          <div role="tabpanel" class="tab-pane fade in active" id="tab-1">
            <div class="contentFull clearfix"><ul>
      <%=raw @gear.description %>
</ul></div>
          </div>
          <div role="tabpanel" class="tab-pane fade" id="tab-0">
            <div class="comment-wrap">
            <div id="ctl00_mainContent_ctl00_ctl00_comment_pnlFeedback" data-type="0" class="commentpanel commentpanel0">
    <div class="journalTools">
        <div class="journalEditor">
            <div id="disqus_thread"></div>

<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://vuive.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        </div>
    </div>
    <div class="clear"></div>
    
    <div class="journalItems">
        
    </div>
    
</div></div>
          </div>
        </div>
      </div>
    </div>
  </div>



<!---->