config/routes.rb
Rails.application.routes.draw do
  get "productbrand/show/gear_brand_id=:id" => "productbrand#show", :as => :productbrand
  get "producttype/show/gear_type_id=:id" => "producttype#show", :as => :producttype
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :chipus
  get "charts/index"
  get "charts/show"
  resources :orders
  # get "store/index"
  resources :line_items
  resources :carts
  resources :brands
  resources :types
  resources :gears
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "phanloai/mouse"
  get "phanloai/keyboard"
  get "phannsx/razer"
  get "phannsx/logitech"
  get "phannsx/corsair"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "store#index", as: "store_index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :gears
  validates :brandname, presence: true, length: {minimum: 5, maximum: 30}
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  $total

  def add_gear(gear)
    current_item = line_items.find_by(gear_id: gear.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(gear_id: gear.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
    $total = line_items.to_a.sum { |item| item.total_price }
  end

  def self.total
    return $total
  end
end

app/models/chipu.rb
class Chipu < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/gear.rb
class Gear < ApplicationRecord
  has_attached_file :image, styles: {medium: "10000x10000>", thumb: "10000x10000>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :brand
  belongs_to :type
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :name, presence: true, length: {minimum: 5, maximum: 20}
  validates :description, presence: true, length: {minimum: 10}
  validates :image, presence: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 1}
  validates :inventory, presence: true, numericality: {greater_than_or_equal_to: 1}
  include PgSearch
  pg_search_scope :search_name, against: [:name], using: {
                                  tsearch: {
                                    prefix: true,
                                  },
                                }

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Items present")
      throw :abort
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :gear, optional: true
  belongs_to :order, optional: true
  belongs_to :cart
  $total

  def total_price
    gear.price * quantity
    $total = gear.price * quantity
  end

  def self.total
    return $total
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  enum pay_type: {
         "Check" => "Check",
         "Credit card" => "Credit card",
         "Purchase order" => "Purchase order",
       }
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :gears
  validates :typename, presence: true, length: {minimum: 5, maximum: 30}
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    gear = Gear.find(params[:gear_id])
    @line_item = @cart.add_gear(gear)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to request.referrer }
        format.json
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def line_item_params
    params.require(:line_item).permit(:gear_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/phanloai_helper.rb
module PhanloaiHelper
end

app/helpers/phannsx_helper.rb
module PhannsxHelper
end

app/helpers/productbrand_helper.rb
module ProductbrandHelper
end

app/helpers/producttype_helper.rb
module ProducttypeHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/template_helper.rb
module TemplateHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gear_id %>
    <%= form.text_field :gear_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
        <tr id="current_item">
                <% else %>
                        <tr>
                                <% end %>
                                        <td>
                                                <%= line_item.quantity %>&times;</td>
                                        <td>
                                                <%= line_item.gear.name %>
                                        </td>
                                        <td class="item_price">
                                                <%= number_to_currency(line_item.total_price) %>
                                        </td>
                                        
                        </tr><br>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
line_item.quantity,
truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }
$('#cart').html("<%=j render(@cart) %>");
$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Gear</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.gear %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gear:</strong>
  <%= @line_item.gear %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>